### ISSUE TITLE
可否提供neo4j的导出文件

### ISSUE THREAD

**Issue by siam1991** [Guoaibo/Text-to-CQL#2]
您好，百度网盘中提供的graphdb文件，受限于neo4j版本，无法直接使用，能否提供csv文件，或者neo4j dump文件

**Comment by siam1991** [comment]
尝试了一下，将百度网盘中提供的graph-all02.db中的文件，复制到neo4j安装目录下的data\databases\neo4j文件夹下（原有的删除），重新启动，可以实现数据库的迁移
我的当前版本是社区版4.4.12，重启过程中，提示版本过低，需要将neo4j.conf的dbms.allow_upgrade=true取消注释，再次尝试重启，则成功。

**Comment by Suchun-sv** [comment]
您好，我在使用docker配置的neo4j中，使用了您的方法导入（即用graph.db文件夹替代neo4j)，但是重启容器之后，显示database不可用“Database "neo4j" is unavailable, its status is "offline". 请问您这边“版本过低的报错信息是什么样的呢？我这边是这个样子的。
![image](https://github.com/Guoaibo/Text-to-CQL/assets/35399433/3bb6f36a-474a-48ef-9972-f66dcfdb73c4)
